import os
import sys
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown
from claude_client import ClaudeDevOps

console = Console()

def review_changed_files():
    """Review files changed in current PR/commit"""
    
    # Get changed files from environment (set by GitHub Actions)
    changed_files_str = os.environ.get("CHANGED_FILES", "")
    
    if not changed_files_str:
        # Fallback: get from git
        import subprocess
        result = subprocess.run(
            ["git", "diff", "--name-only", "HEAD~1", "HEAD"],
            capture_output=True, text=True
        )
        changed_files_str = result.stdout
    
    changed_files = [f.strip() for f in changed_files_str.split('\n') if f.strip()]
    
    if not changed_files:
        console.print("[yellow]No changed files found[/yellow]")
        return
    
    console.print(Panel.fit(
        "[bold blue]🤖 AI PR Reviewer[/bold blue]\n[dim]Powered by Claude AI[/dim]",
        border_style="blue"
    ))
    
    claude = ClaudeDevOps()
    review_results = []
    overall_score = []
    
    for file_path in changed_files:
        if not os.path.exists(file_path):
            continue
            
        ext = os.path.splitext(file_path)[1].lower()
        skip_ext = ['.md', '.txt', '.png', '.jpg', '.gif', '.ico']
        if ext in skip_ext:
            continue
        
        console.print(f"\n[cyan]📝 Reviewing:[/cyan] {file_path}")
        
        try:
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            
            if len(content.strip()) == 0:
                continue
                
            result = claude.review_code(content, file_path)
            review_results.append({"file": file_path, "review": result})
            
            console.print(Panel(
                Markdown(result),
                title=f"[bold blue]📋 {file_path}[/bold blue]",
                border_style="blue"
            ))
            
        except Exception as e:
            console.print(f"[red]Error reviewing {file_path}: {e}[/red]")
    
    # Save review to file for GitHub Actions to use
    if review_results:
        os.makedirs("reports", exist_ok=True)
        with open("reports/pr_review.md", "w") as f:
            f.write("# 🤖 AI Code Review Report\n\n")
            f.write("> Generated by Claude AI DevOps Assistant\n\n")
            for r in review_results:
                f.write(f"## 📄 {r['file']}\n\n{r['review']}\n\n---\n\n")
        
        console.print("\n[green]✅ Review saved to reports/pr_review.md[/green]")

if __name__ == "__main__":
    review_changed_files()